command: [
  "python",
  "app.py"
]

env:
  - name: DATABRICKS_HOST
    value: "e2-demo-field-eng.cloud.databricks.com"
  - name: DATABRICKS_ORG_ID
    value: "1444828305810485"
  - name: DASHBOARD_ID
    value: "01f097746d9d1bbbbc0d7939c55bb781"
  - name: CATALOG
    value: "dbdemos_steventan"
  - name: ADMIN_SCHEMA
    value: "monitoring_admin"
  - name: DATA_SCHEMA
    value: "lakehouse_monitoring"
  - name: OUT_SCHEMA
    value: "lakehouse_monitoring_demo_results"
  - name: SQL_WAREHOUSE_ID
    value: "862f1d757f0424f7"
